version: '3.7'

services:
  redis:
    image: redis
    volumes:
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      devnet:
        aliases:
          - redis
    ports:
      - 6379:6379
    command: redis-server

  api:
    container_name: api
    image: node:12.5-stretch
    networks:
      - devnet
    ports:
      - 9000:9000
    volumes:
      - /code/node_modules
      - ./api:/code
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

    command: bash -c "cd /code && npm install && sleep infinity"
  mongo:
    container_name: mongo
    image: mongo:4.0.9
    networks:
      devnet:
        aliases:
          - mongo
    ports:
      - 27017:27017
networks:
  devnet:
    name: devnet
